name: Jekyll site CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  Compilar:

    runs-on: ubuntu-latest

    steps:
    - name: Fazer o git clone
      uses: actions/checkout@v4
    

    - name: Executando primeiro comando
      run: "echo amo DEVOPS ;)"

    - name: Executando dois ou mais comandos
      run: |
        ls -l
        echo fim do processo
      
        docker run \
        -v ${{ github.workspace }}:/srv/jekyll -v ${{ github.workspace }}/_site:/srv/jekyll/_site \
        jekyll/builder:latest /bin/bash -c "chmod -R 777 /srv/jekyll && jekyll build --future"
